Fixes missing require statement in Fortnox::API
Without this require statement, you get something like:
NameError: uninitialized constant Fortnox::API::Dry
  fortnox-api/lib/fortnox/api.rb:28:in ...